/**
 * Qualifers
 *
 * @module      :: Model
 * @description :: Possible qualifer values.
 * @docs		:: http://sailsjs.org/#!documentation/models
 */
module.exports = {
    attributes: {

        _id: 'integer', // This matches the autogenerated id (by the DB) in the user model (pseudo foreign-key)

        yt_topics: {
            type: 'string'
        },

       yt_videos: {
            type:'json'
        },
        createdAt:{
            type:'INTEGER'
        },
        updatedAt:{
            type:'INTEGER'
        }

    }

};
